<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="move" type="MoveRecord"/>

    <xs:complexType name="MoveRecord">
        <xs:sequence>
            <xs:element name="piece_attack"     type="ChessPiece"/>
            <xs:element name="piece_defend"     type="ChessPiece"/>
            <xs:element name="opt_info"         type="ChessPiece"/>
            <xs:element name="src_square"       type="Coordinate"/>
            <xs:element name="dest_square"      type="Coordinate"/>
            <xs:element name="capture_flag"     type="Flag"/>
            <xs:element name="check_flag"       type="Flag"/>
            <xs:element name="checkmate_flag"   type="Flag"/>
            <xs:element name="promotion_flag"   type="Flag"/>
            <xs:element name="castling_flag"    type="Flag"/>
        </xs:sequence>
    </xs:complexType>

<!-- ======================= Coordinate Definitions ======================== -->
    
    <xs:simpleType name="FileChar">
        <xs:restriction base="xs:string">
            <xs:length value="1"/>
            <xs:pattern value="[a-h]"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="RankChar">
        <xs:restriction base="xs:string">
            <xs:length value="1"/>
            <xs:pattern value="[1-8]"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:complexType name="Coordinate">
        <xs:sequence>
            <xs:element name="file_id" type="FileChar"/>
            <xs:element name="rank_id" type="RankChar"/>
        </xs:sequence>
    </xs:complexType>

<!-- ========================== Type Definitions =========================== -->

    <xs:simpleType name="ChessPiece">
        <xs:restriction base="xs:string">
            <xs:length value="6"/>
            <xs:enumeration value="NONE  "/>
            <xs:enumeration value="PAWN  "/>
            <xs:enumeration value="KNIGHT"/>
            <xs:enumeration value="BISHOP"/>
            <xs:enumeration value="ROOK  "/>
            <xs:enumeration value="QUEEN "/>
            <xs:enumeration value="KING  "/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="Flag">
        <xs:restriction base="xs:string">
            <xs:length value="1"/>
            <xs:enumeration value="Y"/>
            <xs:enumeration value="N"/>
        </xs:restriction>
    </xs:simpleType>

</xs:schema>
