<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform">
    
    <xsl:template name="warning-header">
        <xsl:text>DO NOT TOUCH! AUTOGENERATED FROM XSD&#10;&#10;</xsl:text>
    </xsl:template>

</xsl:stylesheet>
