<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="move" type="MoveRecord"/>

    <xs:complexType name="MoveRecord">
        <xs:all>
            <xs:element name="turn_number"  type="xs:unsignedShort"/>
            <xs:element name="color"        type="PlayerColor"/>
            <xs:element name="piece"        type="ChessPiece"/>
            <xs:element name="source"       type="Coordinate"/>
            <xs:element name="destination"  type="Coordinate"/>
            <xs:element name="capture"      type="xs:boolean"/>
            <xs:element name="check"        type="xs:boolean"/>
            <xs:element name="checkmate"    type="xs:boolean"/>
            <xs:element name="castling"     type="xs:boolean"/>
            <xs:element name="promotion"    type="ChessPiece"/>
        </xs:all>
    </xs:complexType>

<!-- ======================= Coordinate Definitions ======================== -->
    
    <xs:simpleType name="FileChar">
        <xs:restriction base="xs:string">
            <xs:length value="1"/>
            <xs:pattern value="[a-h]"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="RankChar">
        <xs:restriction base="xs:string">
            <xs:length value="1"/>
            <xs:pattern value="[1-8]"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:complexType name="Coordinate">
        <xs:sequence>
            <xs:element name="file" type="FileChar"/>
            <xs:element name="rank" type="RankChar"/>
        </xs:sequence>
    </xs:complexType>

    <!-- <xs:simpleType name="Index">
        <xs:restriction base="xs:integer">
            <xs:minInclusive value="0"/>
            <xs:maxInclusive value="63"/>
        </xs:restriction>
    </xs:simpleType> -->

<!-- ========================== Type Definitions =========================== -->

    <xs:simpleType name="PlayerColor">
        <xs:restriction base="xs:string">
            <xs:enumeration value="WHITE"/>
            <xs:enumeration value="BLACK"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="ChessPiece">
        <xs:restriction base="xs:string">
            <xs:enumeration value="NONE"/>
            <xs:enumeration value="PAWN"/>
            <xs:enumeration value="KNIGHT"/>
            <xs:enumeration value="BISHOP"/>
            <xs:enumeration value="ROOK"/>
            <xs:enumeration value="QUEEN"/>
            <xs:enumeration value="KING"/>
        </xs:restriction>
    </xs:simpleType>

</xs:schema>
